# Generated by Django 5.2.5 on 2025-10-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_minio_object_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PI_LEAFLET', 'PIs, Leaflets'), ('LRD', 'LRDs'), ('GRD_ESCALATION', 'GRDs+Escalations'), ('ONLINE_DATABASE', 'Online Databases-Embase, Pubmed')], max_length=50),
        ),
    ]
