# Generated by Django 5.2.5 on 2025-10-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('pis', 'Pi Leaflet'), ('lrd', 'Lrd'), ('grd', 'Grd Escalation'), ('past_cases', 'Past Cases'), ('online_db', 'Online Databases-Embase, Pubmed')], max_length=50),
        ),
    ]
