# Generated by Django 5.2.5 on 2025-08-13 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=255, unique=True)),
                ('document_type', models.CharField(choices=[('PI', 'pi'), ('LRD', 'lrd'), ('LEAFLET', 'leaflet')], max_length=50)),
                ('source_type', models.CharField(choices=[('UPLOAD', 'upload'), ('API', 'api')], max_length=50)),
                ('source_system', models.CharField(choices=[('UPLOAD', 'upload'), ('API', 'api')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=50)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.document')),
            ],
            options={
                'db_table': 'document_files',
            },
        ),
    ]
