# Generated by Django 5.2.5 on 2025-08-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='source_system',
        ),
        migrations.AddField(
            model_name='document',
            name='file_source',
            field=models.CharField(blank=True, choices=[('UPLOAD', 'upload'), ('ONEDRIVE', 'onedrive'), ('SHAREPOINT', 'sharepoint'), ('GOOGLE_DRIVE', 'google_drive'), ('SALESFORCE', 'salesforce'), ('VEEVA', 'veeva')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_source_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
