# Generated by Django 5.2.5 on 2025-09-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_source_system_document_file_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='minio_object_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
