# Generated by Django 5.1.2 on 2025-10-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PI_LEAFLET', 'PIs, Leaflets'), ('LRD', 'LRDs'), ('GRD_ESCALATION', 'GRDs+Escalations'), ('ONLINE_DB', 'Online Databases-Embase, Pubmed')], max_length=50),
        ),
    ]
