# Generated by Django 5.1.2 on 2025-10-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_document_type'),
        ('documents', '0005_document_is_deleted_alter_document_document_type'),
    ]

    operations = [
    ]
