# Generated by Django 5.1.2 on 2025-10-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llm",
            name="model",
            field=models.CharField(max_length=255),
        ),
    ]
